### ISSUE TITLE
Add capability to edit route

### ISSUE THREAD

**Issue by starnutoditopo** [rogalmic/flight-planner#12]
It would be nice to be able to edit the route, once created.
It should be possible to:

- add, delete, move existing waypoints
- create new waypoints through handles in the middle of an arc.

As an example, see [Leaflet 1.0+ Examples's full demo](https://leaflet.github.io/Leaflet.draw/docs/examples/full.html)

OpenLayers already provides this capability: see the ["Draw and Modify Features" demo](https://openlayers.org/en/latest/examples/draw-and-modify-features.html)

**Comment by starnutoditopo** [comment]
The **Modify** interaction can be used. such as these lines in flight.html, after line 251:
```
const modify = new ol.interaction.Modify({source: source});
map.addInteraction(modify);
```

The code above, however, doesn't behave correctly when locating the point in the geometry.

Maybe the ["Draw and Modify Geodesic Circles" example](https://openlayers.org/en/latest/examples/draw-and-modify-geodesic.html) can be useful.

**Comment by rogalmic** [comment]
Added in https://github.com/rogalmic/flight-planner/pull/14 , please test if possible
